# Generated by Django 2.1.5 on 2019-02-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190211_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y %H:%M:%S']),
        ),
    ]
